### PR TITLE
Feature/add more documentation and fix hints

### LINKED ISSUE #86: CLI examples are inconsistent across docs, prompts, and observed usage
[proposed priority = high] The session exposed inconsistent usage patterns across ndx, n-dx, rex, --help, plan, status, work, and --auto. Audit docs and help output so examples are consistent, minimal, and Windows-friendly. Include canonical examples for orchestrator vs standalone usage.

### PR DESCRIPTION
**Pull request by endash-shal**
this addresses some improper hints being sent out when unapplicable, added a lot more documentation, and tried to normalize and fix the config timeout bug
fixes #86, #151, #39

### CODE REVIEW

File: packages/core/cli-timeout.js [hunk 1]
```diff
@@ -17,6 +17,18 @@
...
 export const DEFAULT_TIMEOUT_MS = 1800000;
 
+/**
+ * Per-command timeout defaults that override DEFAULT_TIMEOUT_MS.
+ * These apply when no per-command or global override is present in config.
+ *
+ * `work` and `self-heal` run full agent loops and are bounded by vendor
+ * session limits (4 hours), so they get a higher default than the global 30 min.
+ */
+const COMMAND_TIMEOUT_DEFAULTS = new Map([
```
Comment (endash-shal) [inline packages/core/cli-timeout.js:27]: timeout change for 4 hours instead 30 min

**Review by dnaniel — COMMENTED** [review]
plz include changeset :D

**Review by dnaniel — APPROVED** [review]
